version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: stawisha_user
      POSTGRES_PASSWORD: stawisha_password
      POSTGRES_DB: stawisha_db
    ports:
      - "5434:5432"
    volumes:
      - stawisha_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - STAWISHA_DB_URL=postgres://stawisha_user:stawisha_password@db:5432/stawisha_db
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  stawisha_data: